// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class Activity
{
    public int Id { get; set; }

    public int BranchId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public decimal Discount { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public bool? IsUsed { get; set; }

    public int? Levels { get; set; }

    public string Description { get; set; }

    public virtual ICollection<ActivityItem> ActivityItems { get; set; } = new List<ActivityItem>();

    public virtual Branch Branch { get; set; }
}