// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class ActivityItem
{
    public int Id { get; set; }

    public int? ActivityId { get; set; }

    public int? ProductId { get; set; }

    public virtual Activity Activity { get; set; }

    public virtual Product Product { get; set; }
}