// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class Article
{
    public int Id { get; set; }

    public int EmployeeId { get; set; }

    public int CategoryId { get; set; }

    public string Title { get; set; }

    public string Contents { get; set; }

    public DateOnly PublishDate { get; set; }

    public DateTime? HideTime { get; set; }

    public bool Status { get; set; }

    public string ImageUrl { get; set; }

    public virtual ArticleCategory Category { get; set; }

    public virtual Employee Employee { get; set; }
}