// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class ArticleCategory
{
    public int Id { get; set; }

    public string Category { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();
}