// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class CartStatus
{
    public int Id { get; set; }

    public string Status { get; set; }

    public virtual ICollection<SeatCart> SeatCarts { get; set; } = new List<SeatCart>();
}