// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class Contact
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Tel { get; set; }

    public string Message { get; set; }

    public DateTime SubmitDate { get; set; }
}