// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class CustomerFeedback
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public DateOnly Date { get; set; }

    public int Rating { get; set; }

    public int? ColdDishId { get; set; }

    public int? SashimiId { get; set; }

    public int? HandRollId { get; set; }

    public int? FriedFoodId { get; set; }

    public int? GrilledFoodId { get; set; }

    public int? SakeId { get; set; }

    public int? BeerId { get; set; }

    public int? LiquorId { get; set; }

    public int? NonAlcoholicDrinkId { get; set; }

    public int? EmployeeId { get; set; }

    public int NumberOfCustomer { get; set; }

    public bool ReturnWilling { get; set; }

    public string Comment { get; set; }

    public virtual Employee Employee { get; set; }
}