// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class Order
{
    public int Id { get; set; }

    public int SeatId { get; set; }

    public int CombinedOrderId { get; set; }

    public DateTime CreateTime { get; set; }

    public int Subtotal { get; set; }

    public virtual CombinedOrder CombinedOrder { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Questionnaire> Questionnaires { get; set; } = new List<Questionnaire>();

    public virtual Seat Seat { get; set; }
}