// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class OrderPayment
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int CombinedOrderId { get; set; }

    public int PaymentMethodId { get; set; }

    public int PaymentStatusId { get; set; }

    public int TotalAmount { get; set; }

    public int Discount { get; set; }

    public int NetAmount { get; set; }

    public DateTime PaymentTime { get; set; }

    public virtual CombinedOrder CombinedOrder { get; set; }

    public virtual Member Member { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual PaymentStatus PaymentStatus { get; set; }
}