// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class OrderDiscount
{
    public int Id { get; set; }

    public int OrderPaymentId { get; set; }

    public int CouponId { get; set; }

    public decimal? AppliedValue { get; set; }
}