// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class Permission
{
    public int Id { get; set; }

    public string JobTitle { get; set; }

    public int? ProductP { get; set; }

    public int? EmployeeP { get; set; }

    public int? OrderP { get; set; }

    public int? BranchP { get; set; }
}