// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class ProductStock
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int BranchId { get; set; }

    public int SafetyStock { get; set; }

    public int Stock { get; set; }

    public int MaxAlertStock { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Product Product { get; set; }
}