// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class PurchaseOrder
{
    public int Id { get; set; }

    public int RecordId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public int UnitCost { get; set; }

    public int? Subtotal { get; set; }

    public virtual Product Product { get; set; }

    public virtual PurchaseRecord Record { get; set; }
}