// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class Questionnaire
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public string SatisfactionLevel { get; set; }

    public string FavoriteDish { get; set; }

    public DateOnly Date { get; set; }

    public int OrderId { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}