// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class Reservation
{
    public int Id { get; set; }

    public int BranchId { get; set; }

    public int SeatId { get; set; }

    public int? MemberId { get; set; }

    public DateTime OrderTime { get; set; }

    public DateTime ReservationTime { get; set; }

    public string Tel { get; set; }

    public string Status { get; set; }

    public int Qty { get; set; }

    public string Name { get; set; }

    public string FillUp { get; set; }

    public string Email { get; set; }

    public int Adult { get; set; }

    public int Child { get; set; }

    public string Message { get; set; }

    public string Random { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Member Member { get; set; }

    public virtual Seat Seat { get; set; }
}