// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class ReservationStatus
{
    public int Id { get; set; }

    public int SeatId { get; set; }

    public int BranchId { get; set; }

    public int ReservationId { get; set; }

    public string Status { get; set; }

    public DateTime ReservationTime { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Seat Seat { get; set; }
}