// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class Reward
{
    public int Id { get; set; }

    public int? CouponId { get; set; }

    public int? MemberId { get; set; }

    public int? Qty { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Member Member { get; set; }
}