// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISPAN.Izakaya.EFModels.Models;

public partial class Seat
{
    public int Id { get; set; }

    public int BranchId { get; set; }

    public string Name { get; set; }

    public string QrcodeLink { get; set; }

    public int Capacity { get; set; }

    public bool Status { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<CartSetting> CartSettings { get; set; } = new List<CartSetting>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<ReservationStatus> ReservationStatuses { get; set; } = new List<ReservationStatus>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual ICollection<SeatCart> SeatCarts { get; set; } = new List<SeatCart>();
}